# Generated by Django 6.0 on 2025-12-13 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promokod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Chegirma foizi (%)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='food',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='nomi',
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.AddField(
            model_name='food',
            name='narxi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='turi',
            field=models.CharField(choices=[('ovqat', 'Ovqat'), ('ichimlik', 'Ichimlik'), ('shirinlik', 'Shirinlik')], default='ovqat', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=255)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('tayyorlanmoqda', 'Tayyorlanmoqda'), ('yolda', 'Yo‘lda'), ('yetkazildi', 'Yetkazildi')], default='yangi', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('promokod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promokod')),
            ],
        ),
        migrations.CreateModel(
            name='BuyurtmaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.buyurtma')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.food')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='chegirma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promokod'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
