# Generated by Django 5.2.6 on 2025-12-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promokod_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
